name: Node.js CI
on:
  push:
    branches: [ principal ]
  pull_request:
    branches: [ principal ]
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Install FFMPEG
        run: sudo apt-get install -y ffmpeg

      - name: Start application with timeout
        run: |
          echo "Démarrage du bot (60 sec max)"
          timeout 60s npm start

      - name: Save state (facultatif)
        run: ./save_state.sh || true
