name: Node.js CI

on:
  push:
    branches:
      - principal
  pull_request:
    branches:
      - principal
  schedule:
    - cron: '0 */6 * * *'  # Toutes les 6 heures

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Référentiel de code
        uses: actions/checkout@v3

      - name: Configurer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installer les dépendances
        run: npm install

      - name: Installer FFMPEG
        run: sudo apt-get install -y ffmpeg

      - name: Démarrer l'application avec timeout
        run: |
          echo "Démarrage de l'application avec délai"
          timeout 2155s npm start || echo "Fin ou arrêt du script"

      - name: Enregistrer l’état (facultatif)
        run: ./save_state.sh
